---
# Install ROS packages task

- name: Install ROS Packages
  apt:
    name: "{{ packages }}"
    allow_unauthenticated: yes
  vars:
    packages: "{{ 'ros-' + ros_distribution + '-' + item }}"
  with_items: "{{ ros_packages }}"
  when: (ros_packages is defined) and (ros_packages is not none)
